# Generated by Django 4.0.10 on 2023-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='regdno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
