# Generated by Django 4.0.10 on 2023-06-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('regdno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
            ],
        ),
    ]
