# Generated by Django 4.0.10 on 2023-06-14 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='type',
            field=models.CharField(choices=[('theory', 'theory'), ('lab', 'lab')], default='lab', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks',
            name='marks',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
