# Generated by Django 4.0.10 on 2023-06-15 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_departments_sections_remove_marks_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='dept_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments'),
        ),
        migrations.AlterField(
            model_name='students',
            name='dept_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments'),
        ),
        migrations.AlterField(
            model_name='students',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sections'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='dept_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments'),
        ),
    ]
