# Generated by Django 4.0.10 on 2023-06-15 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_marks_subject_id_alter_sections_dept_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='credits',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
    ]
